on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: spin up cromwell
        run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/86/cromwell-86.jar
          java -jar cromwell-86.jar server &

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          CROMWELLURL: http://localhost:8000

      - name: cleanup cromwell
        run: kill $(ps -eaf | grep 'cromwell-[0-9][0-9].jar' | awk '{ print $2 }')
